// <auto-generated />
using System;
using ActivityTracking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActivityTracking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251226041723_metodekerja field computerize")]
    partial class metodekerjafieldcomputerize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActivityTracking.Data.ActivityLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int?>("AktivitasID")
                        .HasColumnType("int");

                    b.Property<int?>("AplikasiID")
                        .HasColumnType("int");

                    b.Property<string>("AsalDok")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ComputerNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deskripsi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DigunakanOleh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DurasiMenit")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FrekuensiID")
                        .HasColumnType("int");

                    b.Property<string>("JenisDok")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("MetodeKerjaID")
                        .HasColumnType("int");

                    b.Property<string>("NamaDok")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("Tanggal")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly?>("WaktuMulai")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("WaktuSelesai")
                        .HasColumnType("time");

                    b.HasKey("LogID");

                    b.HasIndex("AktivitasID");

                    b.HasIndex("AplikasiID");

                    b.HasIndex("FrekuensiID");

                    b.HasIndex("MetodeKerjaID");

                    b.HasIndex("UserID");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("ActivityTracking.Data.ActivityLogFile", b =>
                {
                    b.Property<int>("FileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileID"));

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("LogID")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FileID");

                    b.HasIndex("LogID");

                    b.ToTable("ActivityLogFiles");
                });

            modelBuilder.Entity("ActivityTracking.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Bagian")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmployeeID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Jabatan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KomputerNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KomputerType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nama")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipeKaryawan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Unit")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ActivityTracking.Data.MasterActivity", b =>
                {
                    b.Property<int>("AktivitasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AktivitasID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NamaAktivitas")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AktivitasID");

                    b.ToTable("MasterActivities");

                    b.HasData(
                        new
                        {
                            AktivitasID = 1,
                            IsActive = true,
                            NamaAktivitas = "Pemasukan Data"
                        },
                        new
                        {
                            AktivitasID = 2,
                            IsActive = true,
                            NamaAktivitas = "Pencocokan Data"
                        },
                        new
                        {
                            AktivitasID = 3,
                            IsActive = true,
                            NamaAktivitas = "Rekap Data"
                        },
                        new
                        {
                            AktivitasID = 4,
                            IsActive = true,
                            NamaAktivitas = "Laporan Data"
                        },
                        new
                        {
                            AktivitasID = 5,
                            IsActive = true,
                            NamaAktivitas = "Buat Data"
                        });
                });

            modelBuilder.Entity("ActivityTracking.Data.MasterApplication", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NamaAplikasi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ApplicationID");

                    b.ToTable("MasterApplications");

                    b.HasData(
                        new
                        {
                            ApplicationID = 1,
                            IsActive = true,
                            NamaAplikasi = "DTS"
                        },
                        new
                        {
                            ApplicationID = 2,
                            IsActive = true,
                            NamaAplikasi = "Stage/Proman"
                        },
                        new
                        {
                            ApplicationID = 3,
                            IsActive = true,
                            NamaAplikasi = "Entahr"
                        },
                        new
                        {
                            ApplicationID = 4,
                            IsActive = true,
                            NamaAplikasi = "Lainnya"
                        });
                });

            modelBuilder.Entity("ActivityTracking.Data.MasterAsalDok", b =>
                {
                    b.Property<int>("AsalDokID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsalDokID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NamaAsalDok")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AsalDokID");

                    b.ToTable("MasterAsalDoks");

                    b.HasData(
                        new
                        {
                            AsalDokID = 1,
                            IsActive = true,
                            NamaAsalDok = "Cutting"
                        },
                        new
                        {
                            AsalDokID = 2,
                            IsActive = true,
                            NamaAsalDok = "IE"
                        },
                        new
                        {
                            AsalDokID = 3,
                            IsActive = true,
                            NamaAsalDok = "Sewing Line"
                        },
                        new
                        {
                            AsalDokID = 4,
                            IsActive = true,
                            NamaAsalDok = "HRD"
                        },
                        new
                        {
                            AsalDokID = 5,
                            IsActive = true,
                            NamaAsalDok = "Packing"
                        },
                        new
                        {
                            AsalDokID = 6,
                            IsActive = true,
                            NamaAsalDok = "Lainnya"
                        });
                });

            modelBuilder.Entity("ActivityTracking.Data.MasterBagian", b =>
                {
                    b.Property<int>("BagianID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BagianID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NamaBagian")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BagianID");

                    b.ToTable("MasterBagians");

                    b.HasData(
                        new
                        {
                            BagianID = 1,
                            IsActive = true,
                            NamaBagian = "Produksi"
                        },
                        new
                        {
                            BagianID = 2,
                            IsActive = true,
                            NamaBagian = "QC"
                        },
                        new
                        {
                            BagianID = 3,
                            IsActive = true,
                            NamaBagian = "Warehouse"
                        });
                });

            modelBuilder.Entity("ActivityTracking.Data.MasterComputer", b =>
                {
                    b.Property<int>("ComputerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComputerID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NamaComputer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ComputerID");

                    b.ToTable("MasterComputers");

                    b.HasData(
                        new
                        {
                            ComputerID = 1,
                            IsActive = true,
                            NamaComputer = "PC-001"
                        },
                        new
                        {
                            ComputerID = 2,
                            IsActive = true,
                            NamaComputer = "PC-002"
                        },
                        new
                        {
                            ComputerID = 3,
                            IsActive = true,
                            NamaComputer = "PC-003"
                        },
                        new
                        {
                            ComputerID = 4,
                            IsActive = true,
                            NamaComputer = "Laptop-001"
                        },
                        new
                        {
                            ComputerID = 5,
                            IsActive = true,
                            NamaComputer = "Laptop-002"
                        });
                });

            modelBuilder.Entity("ActivityTracking.Data.MasterFrequency", b =>
                {
                    b.Property<int>("FrequencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrequencyID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NamaFrekuensi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FrequencyID");

                    b.ToTable("MasterFrequencies");

                    b.HasData(
                        new
                        {
                            FrequencyID = 1,
                            IsActive = true,
                            NamaFrekuensi = "Per Jam"
                        },
                        new
                        {
                            FrequencyID = 2,
                            IsActive = true,
                            NamaFrekuensi = "Harian"
                        },
                        new
                        {
                            FrequencyID = 3,
                            IsActive = true,
                            NamaFrekuensi = "Mingguan"
                        },
                        new
                        {
                            FrequencyID = 4,
                            IsActive = true,
                            NamaFrekuensi = "Bulanan"
                        },
                        new
                        {
                            FrequencyID = 5,
                            IsActive = true,
                            NamaFrekuensi = "Insidentil"
                        });
                });

            modelBuilder.Entity("ActivityTracking.Data.MasterJabatan", b =>
                {
                    b.Property<int>("JabatanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JabatanID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NamaJabatan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JabatanID");

                    b.ToTable("MasterJabatans");

                    b.HasData(
                        new
                        {
                            JabatanID = 1,
                            IsActive = true,
                            NamaJabatan = "Staff Admin"
                        },
                        new
                        {
                            JabatanID = 2,
                            IsActive = true,
                            NamaJabatan = "Supervisor"
                        },
                        new
                        {
                            JabatanID = 3,
                            IsActive = true,
                            NamaJabatan = "Manager"
                        });
                });

            modelBuilder.Entity("ActivityTracking.Data.MasterJenisDok", b =>
                {
                    b.Property<int>("JenisDokID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JenisDokID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NamaJenisDok")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("JenisDokID");

                    b.ToTable("MasterJenisDoks");

                    b.HasData(
                        new
                        {
                            JenisDokID = 1,
                            IsActive = true,
                            NamaJenisDok = "Excel"
                        },
                        new
                        {
                            JenisDokID = 2,
                            IsActive = true,
                            NamaJenisDok = "PDF"
                        },
                        new
                        {
                            JenisDokID = 3,
                            IsActive = true,
                            NamaJenisDok = "Word"
                        },
                        new
                        {
                            JenisDokID = 4,
                            IsActive = true,
                            NamaJenisDok = "Gambar"
                        },
                        new
                        {
                            JenisDokID = 5,
                            IsActive = true,
                            NamaJenisDok = "Print Out"
                        },
                        new
                        {
                            JenisDokID = 6,
                            IsActive = true,
                            NamaJenisDok = "Tulisan Tangan"
                        },
                        new
                        {
                            JenisDokID = 7,
                            IsActive = true,
                            NamaJenisDok = "Lainnya"
                        });
                });

            modelBuilder.Entity("ActivityTracking.Data.MasterPengguna", b =>
                {
                    b.Property<int>("PenggunaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PenggunaID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NamaPengguna")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PenggunaID");

                    b.ToTable("MasterPenggunas");

                    b.HasData(
                        new
                        {
                            PenggunaID = 1,
                            IsActive = true,
                            NamaPengguna = "Internal"
                        },
                        new
                        {
                            PenggunaID = 2,
                            IsActive = true,
                            NamaPengguna = "Eksternal"
                        },
                        new
                        {
                            PenggunaID = 3,
                            IsActive = true,
                            NamaPengguna = "Pribadi"
                        });
                });

            modelBuilder.Entity("ActivityTracking.Data.MasterUnit", b =>
                {
                    b.Property<int>("UnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NamaUnit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UnitID");

                    b.ToTable("MasterUnits");

                    b.HasData(
                        new
                        {
                            UnitID = 1,
                            IsActive = true,
                            NamaUnit = "Unit A"
                        },
                        new
                        {
                            UnitID = 2,
                            IsActive = true,
                            NamaUnit = "Unit B"
                        },
                        new
                        {
                            UnitID = 3,
                            IsActive = true,
                            NamaUnit = "Unit C"
                        });
                });

            modelBuilder.Entity("ActivityTracking.Data.MasterWorkMethod", b =>
                {
                    b.Property<int>("MethodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MethodID"));

                    b.Property<bool>("Computerize")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NamaMetode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MethodID");

                    b.ToTable("MasterWorkMethods");

                    b.HasData(
                        new
                        {
                            MethodID = 1,
                            Computerize = false,
                            IsActive = true,
                            NamaMetode = "Tulis Tangan"
                        },
                        new
                        {
                            MethodID = 2,
                            Computerize = true,
                            IsActive = true,
                            NamaMetode = "Non Sistem Aplikasi"
                        },
                        new
                        {
                            MethodID = 3,
                            Computerize = true,
                            IsActive = true,
                            NamaMetode = "Email"
                        },
                        new
                        {
                            MethodID = 4,
                            Computerize = true,
                            IsActive = true,
                            NamaMetode = "Sistem Aplikasi"
                        },
                        new
                        {
                            MethodID = 5,
                            Computerize = true,
                            IsActive = true,
                            NamaMetode = "Print"
                        });
                });

            modelBuilder.Entity("ActivityTracking.Data.StaffJamKerja", b =>
                {
                    b.Property<int>("JamKerjaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JamKerjaID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("JamKerja")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("Tanggal")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("JamKerjaID");

                    b.HasIndex("UserId", "Tanggal")
                        .IsUnique();

                    b.ToTable("StaffJamKerjas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ActivityTracking.Data.ActivityLog", b =>
                {
                    b.HasOne("ActivityTracking.Data.MasterActivity", "Aktivitas")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("AktivitasID");

                    b.HasOne("ActivityTracking.Data.MasterApplication", "Aplikasi")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("AplikasiID");

                    b.HasOne("ActivityTracking.Data.MasterFrequency", "Frekuensi")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("FrekuensiID");

                    b.HasOne("ActivityTracking.Data.MasterWorkMethod", "MetodeKerja")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("MetodeKerjaID");

                    b.HasOne("ActivityTracking.Data.ApplicationUser", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aktivitas");

                    b.Navigation("Aplikasi");

                    b.Navigation("Frekuensi");

                    b.Navigation("MetodeKerja");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ActivityTracking.Data.ActivityLogFile", b =>
                {
                    b.HasOne("ActivityTracking.Data.ActivityLog", "ActivityLog")
                        .WithMany("Files")
                        .HasForeignKey("LogID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityLog");
                });

            modelBuilder.Entity("ActivityTracking.Data.StaffJamKerja", b =>
                {
                    b.HasOne("ActivityTracking.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ActivityTracking.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ActivityTracking.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ActivityTracking.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ActivityTracking.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ActivityTracking.Data.ActivityLog", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("ActivityTracking.Data.ApplicationUser", b =>
                {
                    b.Navigation("ActivityLogs");
                });

            modelBuilder.Entity("ActivityTracking.Data.MasterActivity", b =>
                {
                    b.Navigation("ActivityLogs");
                });

            modelBuilder.Entity("ActivityTracking.Data.MasterApplication", b =>
                {
                    b.Navigation("ActivityLogs");
                });

            modelBuilder.Entity("ActivityTracking.Data.MasterFrequency", b =>
                {
                    b.Navigation("ActivityLogs");
                });

            modelBuilder.Entity("ActivityTracking.Data.MasterWorkMethod", b =>
                {
                    b.Navigation("ActivityLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
